import './styles/globals.css';
import Head from 'next/head';

import { DarkModeProvider } from './utils/DarkModeContext';
import { FoldersProvider } from './utils/FoldersContext';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <DarkModeProvider>
      <FoldersProvider>
        <html lang='en'>
          <body>
            <Head>
              <title>Welcome to your Task Manager</title>
              <meta name='description' content='Generated by create next app' />
            </Head>
            {children}
          </body>
        </html>
      </FoldersProvider>
    </DarkModeProvider>
  );
}
